name: Build VScompress Project

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Build Debug
      - name: Build Debug
        run: msbuild VScompress.sln /p:Configuration=Debug /p:Platform=x64 /verbosity:minimal

      # Build Release
      - name: Build Release
        run: msbuild VScompress.sln /p:Configuration=Release /p:Platform=x64 /verbosity:minimal

      # Upload Debug binaries
      - name: Upload Debug Binaries
        uses: actions/upload-artifact@v4
        with:
          name: VScompress-Debug
          path: ./bin/Debug/*

      # Upload Release binaries
      - name: Upload Release Binaries
        uses: actions/upload-artifact@v4
        with:
          name: VScompress-Release
          path: ./bin/Release/*
